### ISSUE TITLE
Help, I'm getting this error

### ISSUE THREAD

**Issue by DiamondOre-eng** [truedl/discord-bot-leveling-system#1]
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Database.connect() done, defined at C:\Users\andre\PycharmProjects\pythonProject\otherthingy.py:13> exception=ConnectionRefusedError(22, 'The remote computer refused the network connection', None, 1225, None)>
Traceback (most recent call last):
File "C:\Users\andre\PycharmProjects\pythonProject\otherthingy.py", line 14, in connect
self.conn = await asyncpg.connect(user=self.user, password=self.password, host='127.0.0.1')
File "C:\Users\andre\PycharmProjects\pythonProject\venv\lib\site-packages\asyncpg\connection.py", line 1718, in connect
return await connect_utils._connect(
File "C:\Users\andre\PycharmProjects\pythonProject\venv\lib\site-packages\asyncpg\connect_utils.py", line 674, in _connect
raise last_error
File "C:\Users\andre\PycharmProjects\pythonProject\venv\lib\site-packages\asyncpg\connect_utils.py", line 663, in _connect
con = await _connect_addr(
File "C:\Users\andre\PycharmProjects\pythonProject\venv\lib\site-packages\asyncpg\connect_utils.py", line 632, in _connect_addr
tr, pr = await asyncio.wait_for(
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\tasks.py", line 483, in wait_for
return fut.result()
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1025, in create_connection
raise exceptions[0]
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1010, in create_connection
sock = await self._connect_sock(
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 924, in _connect_sock
await self.sock_connect(sock, address)
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 702, in sock_connect
return await self._proactor.connect(sock, address)
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 808, in _poll
value = callback(transferred, key, ov)
File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 595, in finish_connect
ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

**Comment by Blue-Gamer48** [comment]
the code ist broken
